FROM node:17.9.0 AS build

WORKDIR /app

ARG VM_HOST
ARG BACKEND_PORT
ARG BUILD_NUM
ARG APP_SECRET
ARG EXPIRES_ACCESS_TOKEN
ARG EXPIRES_REFRESH_TOKEN
ARG MONGO_USER
ARG MONGO_PASS
ARG MONGO_DB_NAME
ARG MONGO_DB_HOST
ARG MONGO_DB_PORT
ARG ADMINISTRATOR_TG
ARG AVAILABLE_TESTERS

ENV VM_HOST=$VM_HOST
ENV BACKEND_PORT=$BACKEND_PORT
ENV BUILD_NUM=$BUILD_NUM
ENV APP_SECRET=$APP_SECRET
ENV EXPIRES_ACCESS_TOKEN=$EXPIRES_ACCESS_TOKEN
ENV EXPIRES_REFRESH_TOKEN=$EXPIRES_REFRESH_TOKEN
ENV MONGO_USER=$MONGO_USER
ENV MONGO_PASS=$MONGO_PASS
ENV MONGO_DB_NAME=$MONGO_DB_NAME
ENV MONGO_DB_HOST=$VM_HOST
ENV MONGO_DB_PORT=$MONGO_DB_PORT
ENV ADMINISTRATOR_TG=$ADMINISTRATOR_TG
ENV AVAILABLE_TESTERS=$AVAILABLE_TESTERS

COPY . .

RUN echo $AVAILABLE_TESTERS > available-user-testers.json

RUN npm ci
RUN npm install pm2 -g

CMD ["pm2-runtime", "start", "ecosystem.config.json"]
